firmware: qcom: Add missing type specifier
Fixes:
drivers/firmware/qcom/tz_log.c:1726:8: error: type specifier missing,
    defaults to 'int' [-Werror,-Wimplicit-int]
static _print_encrpted_qsee_log_stats(struct encrypted_log_info
    *enc_log_info)
~~~~~~ ^
int
1 error generated.

Change-Id: Id3eda0a08b776d6681cb0515e1a0de74f058cce4